"""10-Stage Reproducible Demo Stepper REST API Routes for WindGuard AI (Layer 6).

Source:
- docs/07_srs.md §4.1
- docs/09_technical_design.md §2.6
- docs/12_ui_ux_specification.md §6
- docs/PHASE_6_OWNER_DECISION_RESOLUTION.md §4 (OD-P6-10)
"""

from fastapi import APIRouter, HTTPException, status

from backend.api.schemas import DemoStageResponse
from backend.data.schema import OperatingStatus, TelemetryRecord

router = APIRouter(prefix="/demo", tags=["10-Stage Interactive Demonstration"])

# Deterministic scenario definitions for 10-stage stepper
_DEMO_STAGES = {
    1: {
        "stage_name": "Stage 1: Healthy Fleet Baseline",
        "scenario_type": "S1_BASELINE_HEALTHY",
        "description": "Multi-turbine fleet operating under normal weather transients and balanced thermal dissipation.",
        "expected_status": "NORMAL",
        "injected_fault": None,
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T10:00:00Z",
            turbine_id="WTG-01",
            wind_speed=8.5,
            wind_direction=225.0,
            ambient_temp=28.0,
            active_power=1650.0,
            reactive_power=110.0,
            rotor_speed=14.5,
            generator_speed=1450.0,
            gearbox_bearing_temp=62.0,
            generator_stator_temp=68.0,
            nacelle_temp=32.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    2: {
        "stage_name": "Stage 2: Early Friction Degradation",
        "scenario_type": "S2_GEARBOX_BEARING_DEGRADATION",
        "description": "Initial mechanical friction developing on high-speed shaft bearing of WTG-07.",
        "expected_status": "MONITORING",
        "injected_fault": "Early bearing race wear (+6°C rise)",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T10:10:00Z",
            turbine_id="WTG-07",
            wind_speed=8.5,
            wind_direction=225.0,
            ambient_temp=28.0,
            active_power=1640.0,
            reactive_power=110.0,
            rotor_speed=14.5,
            generator_speed=1450.0,
            gearbox_bearing_temp=68.0,
            generator_stator_temp=69.0,
            nacelle_temp=33.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    3: {
        "stage_name": "Stage 3: Severe Gearbox Bearing Thermal Excursion",
        "scenario_type": "S2_GEARBOX_BEARING_DEGRADATION",
        "description": "High-speed shaft bearing temperature excursion (+16.4°C) with persistent +3.2σ residual on WTG-07.",
        "expected_status": "HIGH_PRIORITY_FAULT",
        "injected_fault": "Severe bearing lubrication breakdown / fatigue spalling",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T10:20:00Z",
            turbine_id="WTG-07",
            wind_speed=8.5,
            wind_direction=225.0,
            ambient_temp=28.0,
            active_power=1620.0,
            reactive_power=110.0,
            rotor_speed=14.4,
            generator_speed=1440.0,
            gearbox_bearing_temp=78.4,
            generator_stator_temp=70.0,
            nacelle_temp=35.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    4: {
        "stage_name": "Stage 4: Aerodynamic Pitch Misalignment Deficit",
        "scenario_type": "S3_PITCH_ASYMMETRY",
        "description": "Blade pitch asymmetry (+2.5° offset) causing 18% aerodynamic power conversion deficit on WTG-03.",
        "expected_status": "AERODYNAMIC_FAULT",
        "injected_fault": "Blade pitch calibration drift (+2.5°)",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T10:30:00Z",
            turbine_id="WTG-03",
            wind_speed=8.5,
            wind_direction=220.0,
            ambient_temp=28.0,
            active_power=1350.0,
            reactive_power=95.0,
            rotor_speed=13.8,
            generator_speed=1380.0,
            gearbox_bearing_temp=61.5,
            generator_stator_temp=66.0,
            nacelle_temp=31.0,
            pitch_angle=3.0,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    5: {
        "stage_name": "Stage 5: Grid Curtailment & Ambient Heatwave",
        "scenario_type": "S4_GRID_CURTAILMENT_HEATWAVE",
        "description": "Active power capped at 1000 kW under grid dispatch command during 42°C summer heatwave. Context correctly suppresses alarm.",
        "expected_status": "CURTAILED_SUPPRESSED",
        "injected_fault": None,
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T10:40:00Z",
            turbine_id="WTG-05",
            wind_speed=9.0,
            wind_direction=230.0,
            ambient_temp=42.0,
            active_power=1000.0,
            reactive_power=80.0,
            rotor_speed=12.5,
            generator_speed=1250.0,
            gearbox_bearing_temp=72.0,
            generator_stator_temp=78.0,
            nacelle_temp=44.0,
            pitch_angle=12.0,
            is_curtailed=True,
            operating_status=OperatingStatus.CURTAILED,
        ),
    },
    6: {
        "stage_name": "Stage 6: Low-Wind Sub-Cut-In Idling",
        "scenario_type": "S1_BASELINE_HEALTHY",
        "description": "Wind speed (2.2 m/s) below cut-in threshold (3.0 m/s). Context engine suppresses low power deficit.",
        "expected_status": "IDLING_SUPPRESSED",
        "injected_fault": None,
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T10:50:00Z",
            turbine_id="WTG-02",
            wind_speed=2.2,
            wind_direction=180.0,
            ambient_temp=27.0,
            active_power=0.0,
            reactive_power=0.0,
            rotor_speed=2.0,
            generator_speed=200.0,
            gearbox_bearing_temp=35.0,
            generator_stator_temp=38.0,
            nacelle_temp=29.0,
            pitch_angle=85.0,
            is_curtailed=False,
            operating_status=OperatingStatus.IDLING,
        ),
    },
    7: {
        "stage_name": "Stage 7: Thermocouple Sensor Disconnection",
        "scenario_type": "S5_SENSOR_DROPOUT",
        "description": "Thermocouple disconnect yielding unphysical -15.0°C reading on WTG-09 while ambient is 30°C.",
        "expected_status": "SENSOR_ERROR",
        "injected_fault": "Sensor dropout / thermocouple disconnection",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T11:00:00Z",
            turbine_id="WTG-09",
            wind_speed=8.0,
            wind_direction=225.0,
            ambient_temp=30.0,
            active_power=1500.0,
            reactive_power=100.0,
            rotor_speed=14.0,
            generator_speed=1400.0,
            gearbox_bearing_temp=-15.0,
            generator_stator_temp=67.0,
            nacelle_temp=32.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    8: {
        "stage_name": "Stage 8: Generator Stator Airflow Restriction",
        "scenario_type": "S2_GEARBOX_BEARING_DEGRADATION",
        "description": "Generator stator thermal excursion (+22°C above baseline) indicating cooling duct blockage on WTG-04.",
        "expected_status": "GENERATOR_THERMAL_FAULT",
        "injected_fault": "Generator cooling fan inlet filter clogging",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T11:10:00Z",
            turbine_id="WTG-04",
            wind_speed=9.5,
            wind_direction=225.0,
            ambient_temp=30.0,
            active_power=1850.0,
            reactive_power=120.0,
            rotor_speed=15.0,
            generator_speed=1500.0,
            gearbox_bearing_temp=64.0,
            generator_stator_temp=118.5,
            nacelle_temp=36.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    9: {
        "stage_name": "Stage 9: Persistent Multi-Signal Critical Anomaly",
        "scenario_type": "S2_GEARBOX_BEARING_DEGRADATION",
        "description": "6 consecutive intervals of severe thermal excursion yielding CRITICAL priority score (85+) on WTG-07.",
        "expected_status": "CRITICAL_MAINTENANCE_REQUIRED",
        "injected_fault": "Bearing catastrophic failure risk requiring urgent inspection",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T11:20:00Z",
            turbine_id="WTG-07",
            wind_speed=9.0,
            wind_direction=225.0,
            ambient_temp=31.0,
            active_power=1680.0,
            reactive_power=115.0,
            rotor_speed=14.8,
            generator_speed=1480.0,
            gearbox_bearing_temp=84.2,
            generator_stator_temp=72.0,
            nacelle_temp=37.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
    10: {
        "stage_name": "Stage 10: Fleet Multi-Turbine Dispatch Triage",
        "scenario_type": "S1_BASELINE_HEALTHY",
        "description": "Comprehensive multi-turbine state demonstrating triage prioritization, financial ranking, and operator workflow.",
        "expected_status": "FLEET_TRIAGE_ACTIVE",
        "injected_fault": "Multi-turbine operational snapshot",
        "telemetry": TelemetryRecord(
            timestamp="2026-09-20T11:30:00Z",
            turbine_id="WTG-01",
            wind_speed=8.5,
            wind_direction=225.0,
            ambient_temp=28.0,
            active_power=1650.0,
            reactive_power=110.0,
            rotor_speed=14.5,
            generator_speed=1450.0,
            gearbox_bearing_temp=62.0,
            generator_stator_temp=68.0,
            nacelle_temp=32.0,
            pitch_angle=0.5,
            is_curtailed=False,
            operating_status=OperatingStatus.RUNNING,
        ),
    },
}


@router.get("/stage/{stage_id}", response_model=DemoStageResponse)
def get_demo_stage(stage_id: int) -> DemoStageResponse:
    """Returns deterministic pre-configured telemetry state for the requested demo stage (1 to 10)."""
    if stage_id not in _DEMO_STAGES:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Demo stage '{stage_id}' is invalid. Supported demo stages are 1 through 10.",
        )

    stage_data = _DEMO_STAGES[stage_id]
    return DemoStageResponse(
        stage_id=stage_id,
        stage_name=stage_data["stage_name"],
        scenario_type=stage_data["scenario_type"],
        description=stage_data["description"],
        telemetry=stage_data["telemetry"],
        expected_status=stage_data["expected_status"],
        injected_fault=stage_data["injected_fault"],
    )
